# Generated by Django 2.1.4 on 2019-01-29 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_auto_20190120_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('class_name', models.CharField(choices=[('FactorBuyBreakXd', '海龟买'), ('AbuDoubleMaBuy', '双均线买')], editable=False, max_length=256, verbose_name='策略')),
            ],
            options={
                'verbose_name': '买策略',
                'verbose_name_plural': '买策略',
            },
        ),
        migrations.CreateModel(
            name='FactorSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('class_name', models.CharField(choices=[('FactorSellBreakXd', '海龟卖'), ('AbuDoubleMaSell', '双均线卖')], editable=False, max_length=256, verbose_name='策略')),
            ],
            options={
                'verbose_name': '卖策略',
                'verbose_name_plural': '卖策略',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.CharField(max_length=64, verbose_name='买入日期')),
                ('buy_price', models.CharField(max_length=64, verbose_name='买入价格')),
                ('buy_cnt', models.CharField(max_length=64, verbose_name='买入数量')),
                ('buy_factor', models.CharField(max_length=64, verbose_name='买入策略')),
                ('symbol', models.CharField(max_length=64, verbose_name='股票编号')),
                ('buy_pos', models.CharField(max_length=64, verbose_name='买入滑dian')),
                ('buy_type_str', models.CharField(max_length=64, verbose_name='买入类型')),
                ('expect_direction', models.CharField(max_length=64, verbose_name='预期方向')),
                ('sell_type_extra', models.CharField(max_length=64, verbose_name='卖出策略')),
                ('sell_date', models.CharField(max_length=64, verbose_name='卖出日期')),
                ('sell_price', models.CharField(max_length=64, verbose_name='卖出价格')),
                ('sell_type', models.CharField(max_length=64, verbose_name='卖出类型')),
                ('ml_features', models.CharField(blank=True, max_length=64, null=True, verbose_name='MLI特征')),
                ('key', models.CharField(max_length=64, verbose_name='关键字')),
                ('profit', models.CharField(max_length=64, verbose_name='盈利')),
                ('result', models.CharField(max_length=64, verbose_name='结果')),
                ('profit_cg', models.CharField(max_length=64, verbose_name='盈利比')),
                ('profit_cg_hunder', models.CharField(max_length=64, verbose_name='盈利率')),
                ('keep_days', models.CharField(max_length=64, verbose_name='持股天数')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '回测订单',
                'verbose_name_plural': '回测订单',
            },
        ),
        migrations.CreateModel(
            name='RangeBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(verbose_name='开始')),
                ('end', models.IntegerField(verbose_name='结束')),
                ('step', models.FloatField(verbose_name='增量')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('class_name', models.CharField(choices=[('FactorSellBreakXd', '海龟卖'), ('AbuDoubleMaSell', '双均线卖')], editable=False, max_length=256, verbose_name='策略')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RangeSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(verbose_name='开始')),
                ('end', models.IntegerField(verbose_name='结束')),
                ('step', models.FloatField(verbose_name='增量')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('class_name', models.CharField(choices=[('FactorSellBreakXd', '海龟卖'), ('AbuDoubleMaSell', '双均线卖')], editable=False, max_length=256, verbose_name='策略')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('start', models.DateField(verbose_name='开始')),
                ('end', models.DateField(verbose_name='结束')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('status', models.CharField(blank=True, default='新建', max_length=64, verbose_name='状态')),
                ('read_cash', models.IntegerField(verbose_name='初始化资金')),
            ],
        ),
        migrations.CreateModel(
            name='FactorBuyBreakXd',
            fields=[
                ('factorbuy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='runloop.FactorBuy')),
                ('xd', models.CharField(max_length=64, verbose_name='周期')),
            ],
            options={
                'verbose_name': '海龟买入',
                'verbose_name_plural': '海龟买入',
            },
            bases=('runloop.factorbuy',),
        ),
        migrations.CreateModel(
            name='FactorBuyRangeBreakXd',
            fields=[
                ('rangebuy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='runloop.RangeBuy')),
            ],
            options={
                'verbose_name': '海龟买入范围',
                'verbose_name_plural': '海龟买入范围',
            },
            bases=('runloop.rangebuy',),
        ),
        migrations.CreateModel(
            name='FactorSellBreakXd',
            fields=[
                ('factorsell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='runloop.FactorSell')),
                ('xd', models.CharField(max_length=64, verbose_name='周期')),
            ],
            options={
                'verbose_name': '海龟卖出',
                'verbose_name_plural': '海龟卖出',
            },
            bases=('runloop.factorsell',),
        ),
        migrations.CreateModel(
            name='FactorSellRangeBreakXd',
            fields=[
                ('rangesell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='runloop.RangeSell')),
            ],
            options={
                'verbose_name': '海龟卖出范围',
                'verbose_name_plural': '海龟卖出范围',
            },
            bases=('runloop.rangesell',),
        ),
        migrations.CreateModel(
            name='RunGridSearch',
            fields=[
                ('runbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='runloop.RunBase')),
                ('factor_buys', models.ManyToManyField(related_name='factor_buy_groups', to='runloop.RangeBuy', verbose_name='买策略组合')),
                ('factor_sells', models.ManyToManyField(related_name='factor_sell_groups', to='runloop.RangeSell', verbose_name='卖策略组合')),
            ],
            options={
                'verbose_name': 'GridSearch',
                'verbose_name_plural': 'GridSearch',
            },
            bases=('runloop.runbase',),
        ),
        migrations.CreateModel(
            name='RunLoopGroup',
            fields=[
                ('runbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='runloop.RunBase')),
                ('factor_buys', models.ManyToManyField(related_name='factor_buy_groups', to='runloop.FactorBuy', verbose_name='买策略组合')),
                ('factor_sells', models.ManyToManyField(related_name='factor_sell_groups', to='runloop.FactorSell', verbose_name='卖策略组合')),
            ],
            options={
                'verbose_name': '回测',
                'verbose_name_plural': '回测',
            },
            bases=('runloop.runbase',),
        ),
        migrations.AddField(
            model_name='runbase',
            name='stocks',
            field=models.ManyToManyField(related_name='stock_groups', to='base.Stock', verbose_name='股票组合'),
        ),
        migrations.AddField(
            model_name='orders',
            name='run_loop_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='runloop.RunLoopGroup', verbose_name='回测'),
        ),
    ]
