# Generated by Django 2.1.4 on 2019-01-29 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runloop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorBuyRangeBreakXd',
            fields=[
                ('factorbuy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='runloop.FactorBuy')),
                ('start', models.IntegerField(verbose_name='开始')),
                ('end', models.IntegerField(verbose_name='结束')),
                ('step', models.FloatField(verbose_name='增量')),
            ],
            options={
                'verbose_name': '海龟买入范围',
                'verbose_name_plural': '海龟买入范围',
            },
            bases=('runloop.factorbuy', models.Model),
        ),
    ]
