# Generated by Django 2.1.4 on 2019-02-13 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
        ('runloop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runloopgroup',
            name='positions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='position.Position', verbose_name='仓位管理'),
        ),
    ]
