# Generated by Django 2.1.5 on 2019-01-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runloop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorbuy',
            name='class_name',
            field=models.CharField(choices=[('FactorBuyBreakXd', '海龟买'), ('AbuDoubleMaBuy', '双均线买')], editable=False, max_length=256, verbose_name='策略'),
        ),
        migrations.AlterField(
            model_name='factorsell',
            name='class_name',
            field=models.CharField(choices=[('FactorSellBreakXd', '海龟卖'), ('AbuDoubleMaSell', '双均线卖')], editable=False, max_length=256, verbose_name='策略'),
        ),
    ]
