# Generated by Django 2.1.4 on 2019-02-01 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runloop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorBuyDoubleMa',
            fields=[
                ('factorbuy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='runloop.FactorBuy')),
                ('slow_int', models.IntegerField(verbose_name='慢线(-1:为自动)')),
                ('fast_int', models.IntegerField(verbose_name='快线(-1:为自动)')),
            ],
            options={
                'verbose_name': '双均线买',
                'verbose_name_plural': '双均线买',
            },
            bases=('runloop.factorbuy',),
        ),
        migrations.CreateModel(
            name='FactorSellDoubleMa',
            fields=[
                ('factorsell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='runloop.FactorSell')),
                ('slow_int', models.IntegerField(verbose_name='慢线')),
                ('fast_int', models.IntegerField(verbose_name='快线')),
            ],
            options={
                'verbose_name': '双均线卖',
                'verbose_name_plural': '双均线卖',
            },
            bases=('runloop.factorsell',),
        ),
    ]
