# Generated by Django 2.1.4 on 2019-01-10 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runloop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorBuyBreakXd',
            fields=[
                ('factorbuy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='runloop.FactorBuy')),
                ('xd', models.CharField(max_length=64, verbose_name='周期')),
            ],
            options={
                'verbose_name': '海龟策略',
                'verbose_name_plural': '海龟策略',
            },
            bases=('runloop.factorbuy',),
        ),
        migrations.AlterField(
            model_name='factorbuy',
            name='name',
            field=models.TextField(max_length=64, verbose_name='名称'),
        ),
    ]
