# Generated by Django 2.1.4 on 2019-01-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190120_1626'),
        ('runloop', '0002_auto_20190120_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.CharField(max_length=64, verbose_name='买入日期')),
                ('buy_price', models.CharField(max_length=64, verbose_name='买入价格')),
                ('buy_cnt', models.CharField(max_length=64, verbose_name='买入数量')),
                ('buy_factor', models.CharField(max_length=64, verbose_name='买入策略')),
                ('symbol', models.CharField(max_length=64, verbose_name='买入策略')),
                ('buy_pos', models.CharField(max_length=64, verbose_name='买入滑dian')),
                ('buy_type_str', models.CharField(max_length=64, verbose_name='买入类型')),
                ('expect_direction', models.CharField(max_length=64, verbose_name='预期方向')),
                ('sell_type_extra', models.CharField(max_length=64, verbose_name='卖出策略')),
                ('sell_date', models.CharField(max_length=64, verbose_name='卖出日期')),
                ('sell_price', models.CharField(max_length=64, verbose_name='卖出价格')),
                ('sell_type', models.CharField(max_length=64, verbose_name='卖出类型')),
                ('ml_features', models.CharField(blank=True, max_length=64, null=True, verbose_name='MLI特征')),
                ('key', models.CharField(max_length=64, verbose_name='关键字')),
                ('profit', models.CharField(max_length=64, verbose_name='盈利')),
                ('result', models.CharField(max_length=64, verbose_name='结果')),
                ('profit_cg', models.CharField(max_length=64, verbose_name='盈利比')),
                ('profit_cg_hunder', models.CharField(max_length=64, verbose_name='盈利率')),
                ('keep_days', models.CharField(max_length=64, verbose_name='持股天数')),
                ('run_loop_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='runloop.RunLoopGroup')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Stock')),
            ],
            options={
                'verbose_name': '回测订单',
                'verbose_name_plural': '回测订单',
            },
        ),
    ]
