# Generated by Django 2.1.4 on 2019-02-01 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runloop', '0002_factorbuydoublema_factorselldoublema'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorBuySDBreak',
            fields=[
                ('factorbuybreakxd_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='runloop.FactorBuyBreakXd')),
                ('poly', models.IntegerField(verbose_name='拟合')),
            ],
            options={
                'verbose_name': '平稳突破',
                'verbose_name_plural': '平稳突破',
            },
            bases=('runloop.factorbuybreakxd',),
        ),
    ]
