# Generated by Django 2.1.4 on 2019-01-29 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runloop', '0002_factorbuyrangebreakxd'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorSellRangeBreakXd',
            fields=[
                ('factorsell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='runloop.FactorSell')),
                ('start', models.IntegerField(verbose_name='开始')),
                ('end', models.IntegerField(verbose_name='结束')),
                ('step', models.FloatField(verbose_name='增量')),
            ],
            options={
                'verbose_name': '海龟卖出范围',
                'verbose_name_plural': '海龟卖出范围',
            },
            bases=('runloop.factorsell', models.Model),
        ),
    ]
