# Generated by Django 2.1.5 on 2019-01-27 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runloop', '0003_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='run_loop_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='runloop.RunLoopGroup', verbose_name='回测'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Stock', verbose_name='股票'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='symbol',
            field=models.CharField(max_length=64, verbose_name='股票编号'),
        ),
    ]
