# Generated by Django 2.1.4 on 2019-02-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runloop', '0003_factorbuysdbreak'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factorbuysdbreak',
            options={'verbose_name': '平稳突破买', 'verbose_name_plural': '平稳突破买'},
        ),
        migrations.AlterField(
            model_name='factorbuybreakxd',
            name='xd',
            field=models.IntegerField(verbose_name='周期'),
        ),
    ]
