# Generated by Django 2.1.4 on 2019-01-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('factor_type', models.CharField(choices=[('buy', '买'), ('sell', '卖')], max_length=32)),
                ('customer_id', models.CharField(max_length=128)),
                ('create_time', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factor',
                'verbose_name_plural': 'Factor',
            },
        ),
    ]
