# Generated by Django 2.1.4 on 2019-01-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0003_factor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='customer_id',
        ),
    ]
