# Generated by Django 2.1.4 on 2019-01-07 03:50

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0004_remove_factor_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Param',
                'verbose_name_plural': 'Param',
            },
        ),
        migrations.AlterModelManagers(
            name='factor',
            managers=[
                ('_factor_params', django.db.models.manager.Manager()),
            ],
        ),
    ]
