# Generated by Django 2.1.4 on 2019-01-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0005_auto_20190107_1150'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='factor',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='factor',
            name='params',
            field=models.ManyToManyField(blank=True, related_name='factors', to='his.Param', verbose_name='Params'),
        ),
    ]
