# Generated by Django 2.1.4 on 2019-01-08 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factorbuy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorBuyBreakXd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='策略名称', editable=False, max_length=64)),
                ('xd', models.TextField(verbose_name='周期')),
                ('create_time', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '海龟策略',
                'verbose_name_plural': '海龟策略',
            },
        ),
        migrations.RemoveField(
            model_name='factorbuy',
            name='user',
        ),
        migrations.DeleteModel(
            name='FactorBuy',
        ),
    ]
